version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: logicoffee/hakyll_netlify:lts-16.31
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - stack-{{ .Branch }}-{{ checksum  "stack.yaml" }}
            - stack-{{ .Branch }}-
            - stack-
      - run:
          name: Resolve Dependencies
          command: stack build --dependencies-only -j1
      - save_cache:
          name: Cache Dependencies
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build Site App
          command: stack build --pedantic -j1
      - run:
          name: Generate Static Site
          command: stack exec sharpknock rebuild
      - run:
          name: Publish to Netlify
          command: netlify deploy --dir=_site --prod
